//Genericified binary file storage...Fixed sized records...
//similar to as previous (pr6.4) where it was actually storing the Student struct...
//here since it is geneicified, we can store any data we want..either be primitive or user defined as we'll see while testing...
//almost all the implementation are identical, one extra argument recordSize is passed to the every function because we will be dealing with any data type and we wont know their size...
//also at oeprations as seen in deleteRecord(), where we need temporary buffer to store the bytes, we are dynamically allocating the space and type will be void*, ofcourse...BECAUSE WE DONT KNOW THE DATA TYPE WE ARE DEALING WITH..
//PS: test is generated by chatGPT..

#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>

int countRecords(FILE *fp,int *count,size_t recordSize)
{
    int result=fseek(fp,0,SEEK_END);
    if(result !=0)
    {
        printf("Error seeking to the end of the file!");
        return -1;
    }
    long size=ftell(fp);
    if (size == -1L)
        return -1;
    *count =  (int)(size / (long)recordSize);
    return 0;
}

int getRecord(FILE *fp,void *buffer,int idx, size_t recordSize)
{
    int count;
    countRecords(fp,&count,recordSize);
    if(idx < 0 || idx >= count )
    {
        printf("Invalid Index!");
        return -1;
    }
    long offset = (long)idx * recordSize;
    int result = fseek(fp,offset,SEEK_SET);
    if(result == 0)
    {

        if (fread(buffer, recordSize, 1, fp) != 1)
            return -1;
        return 0;
    }
    else
    {
        printf("Error seeking file to the index position!");
        return -1;
    }
}

int updateRecord(FILE *fp,void *srcBuffer,int idx, size_t recordSize)
{
    long offset = (long)idx * recordSize;

    int result = fseek(fp,offset,SEEK_SET);
    if(result == 0)
    {
        fwrite(srcBuffer,recordSize,1,fp);
        return 0;
    }
    else
    {
        printf("Error seeking file to the index position!");
        return -1;
    }
}

int addRecord(FILE *fp,void *srcBuffer, size_t recordSize)
{
    int result=fseek(fp,0,SEEK_END);
    if(result !=0)
    {
        printf("Error seeking to the end of the file!");
        return -1;
    }
    fwrite(srcBuffer,recordSize,1,fp);
    return 0;
}

int deleteRecord(FILE *fp, int idx, size_t recordSize)
{
    int count=0;
    countRecords(fp,&count,recordSize);
    if(count == 0)
    {
        printf("Empty file!");
        return -1;
    }
    if(idx < 0 || idx >= count)
    {
        printf("Invalid index!");
        return -1;
    }
    void *buffer = malloc(recordSize);
    if (buffer == NULL)
        return -1;
    while(idx < count -1)
    {
        fseek(fp,(long)(idx+1) * recordSize,SEEK_SET);
        fread(buffer,recordSize,1,fp);
        fseek(fp, (long)idx * recordSize,SEEK_SET);
        fwrite(buffer,recordSize,1,fp);
        idx++;
    }

    free(buffer);

    long truncateSize = (long)(count-1) * (long)recordSize;

    if(fflush(fp)!= 0)
    {
        perror("fflush error!");
        return -1;
    }
    if(ftruncate(fileno(fp),truncateSize) !=0)
    {

        printf("Truncate Error!");
        return -1;
    }

    return 0;

}

//=============================TESTS========================================
/* ================= PRODUCT TEST ================= */
typedef struct
{
    int id;
    char name[100];
    float price;
} Product;


void testProducts()
{
    printf("\n========== PRODUCT TEST ==========\n");

    Product products[] =
    {
        {1, "Keyboard", 2500.0f},
        {2, "Mouse", 1200.0f},
        {3, "Monitor", 25000.0f},
        {4, "Headphones", 3500.0f}
    };

    FILE *fp = fopen("products.dat", "w+b");

    if (fp == NULL)
    {
        perror("products.dat");
        return;
    }

    size_t recordSize = sizeof(Product);

    /* Add */
    for (int i = 0; i < 4; i++)
        addRecord(fp, &products[i], recordSize);

    /* Get */
    Product p;

    printf("\nGET record 2:\n");

    if (getRecord(fp, &p, 2, recordSize) == 0)
    {
        printf("%d | %s | %.2f\n",
               p.id,
               p.name,
               p.price);
    }

    /* Update */
    Product updated =
    {3, "Gaming Monitor", 45000.0f};

    updateRecord(fp, &updated, 2, recordSize);

    printf("\nAfter UPDATE:\n");

    getRecord(fp, &p, 2, recordSize);

    printf("%d | %s | %.2f\n",
           p.id,
           p.name,
           p.price);

    /* Delete */
    deleteRecord(fp, 1, recordSize);

    printf("\nAfter DELETE index 1:\n");

    int count;

    countRecords(fp, &count, recordSize);

    for (int i = 0; i < count; i++)
    {
        getRecord(fp, &p, i, recordSize);

        printf("%d | %s | %.2f\n",
               p.id,
               p.name,
               p.price);
    }

    fclose(fp);
}


/* ================= INT TEST ================= */

void testInts()
{
    printf("\n========== INT TEST ==========\n");

    int numbers[] =
    {
        10, 20, 30, 40, 50
    };

    FILE *fp = fopen("ints.dat", "w+b");

    if (fp == NULL)
    {
        perror("ints.dat");
        return;
    }

    size_t recordSize = sizeof(int);

    /* Add */
    for (int i = 0; i < 5; i++)
        addRecord(fp, &numbers[i], recordSize);

    /* Get */
    int x;

    getRecord(fp, &x, 2, recordSize);

    printf("\nGET index 2: %d\n", x);

    /* Update */
    int newValue = 999;

    updateRecord(fp, &newValue, 2, recordSize);

    getRecord(fp, &x, 2, recordSize);

    printf("After UPDATE: %d\n", x);

    /* Delete */
    deleteRecord(fp, 1, recordSize);

    printf("\nAfter DELETE index 1:\n");

    int count;

    countRecords(fp, &count, recordSize);

    for (int i = 0; i < count; i++)
    {
        getRecord(fp, &x, i, recordSize);

        printf("%d\n", x);
    }

    fclose(fp);
}


/* ================= MAIN ================= */

int main()
{
    testProducts();

    testInts();

    return 0;
}
